[build]
target = "thumbv8m.main-none-eabi"

[profile.release-with-debug]
inherits = "release"
debug = true


[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip=STM32H503RB"

[env]
DEFMT_LOG = "info"